languageCode = "en"
languageName = "English"
weight = 1
title = "Cyprian 'Q3rkses' Osinski"

[params]
  displayName = "EN"
  isoCode = "en"

[params.author]
  name = "Cyprian"
  image = "img/cyp.jpg"
  headline = "Control Engineering / Cybernetics & Robotics — NTNU"
  bio = "One day i will think before i speak and you shall be astounded, however that day is not today."
  links = [
    { github = "https://github.com/Q3rkses" },
  ]
